### ISSUE TITLE
rx library implementation?

### ISSUE THREAD

**Issue by vittod** [ReactiveX/learnrx#171] opened 2018-04-27 12:51 UTC
I just tried to pick up my exercises in this great training tool and can't get past exercise 3. 
My console tells me theres a problem loading the RX recources.

**Comment by thoFurman** [comment] 2018-04-30 10:49
You can run the page local if change the index.html in line 5043 from 
<script src="https://unpkg.com/@reactivex/rxjs/dist/global/Rx.js"></script> to 
<script src="https://unpkg.com/@reactivex/rxjs@5.5.5/dist/global/Rx.js"></script>. 
This worked for me until they change the resources online.

**Comment by harveysanders** [comment] 2018-05-03 01:18
+1
FYI:
`GET to  https://unpkg.com/@reactivex/rxjs@6.0.0/dist/global/Rx.js` responds with
"Cannot find module "/dist/global/Rx.js" in package @reactivex/rxjs@6.0.0"

**Comment by seanpoulter** [comment] 2019-03-07 15:39
This is a duplicate of #173 which can also be closed. It was resolved by PR #170.

**Closed as completed** 2019-03-07 16:36 UTC
