### ISSUE TITLE
reduce().map() ? ex20

### ISSUE THREAD

**Issue by 511121418** [ReactiveX/learnrx#150] opened 2016-07-31 16:12 UTC
#### Issue 1 Description

During ex 20, when I checked the solution I noticed something weird, why using map() after this reduce ? this reduce doesn't return an array so it doesn't compile. (I included concatMap just to be sure).
### Screenshoot

![sans titre](https://cloud.githubusercontent.com/assets/10143821/17277679/21f1307a-5749-11e6-865b-92903b451ede.png)
#### Issue 2 Description

My solution doesn't valid though I got the right answer.
### Screenshoot

![sans titre](https://cloud.githubusercontent.com/assets/10143821/17277670/db334aa6-5748-11e6-91b2-e1db39cef5f6.png)
#### My Code

``` js
return movieLists
    .concatMap(movie => movie.videos
        .map(v => {
            v.boxarts = v.boxarts
                .reduce((a, b) => a.width * a.height < b.width * b.height ? a : b)
            return { id: v.id, title: v.title, boxart: v.boxarts.url}
        })
    );
```
#### Browser Information

- Browser Name, Version: Firefox 47.0.1 and Google chrome 
- Operating System: win 7
- Mobile, Desktop, or Tablet: Desktop 

Hope this will help despite my bad english.
Have a nice day.

**Comment by rotexhawk** [comment] 2016-08-10 15:33
Yes there seems to be a bug in exercise 20. It passes if you run it in the website but if you run it externally it will give you an error where that last .map() is.

**Comment by seanpoulter** [comment] 2019-03-09 04:42
**CC**: You can probably close this as a duplicate of #44 @morenoh149.

<br/>

Good catch! It seems like a bug if you run `reduce(...).map` outside of the site but this is actually intentional. In Exercise 16 we write our own implementation of `Array.prototype.reduce` that returns the result in an `Array`. It has this little note:

> Let's add a reduce() function to the Array type. Like map. Take note **this is different from the reduce in ES5, which returns a value instead of an Array!**

I found it confusing too. This was an intentional design choice that is discussed in #44. I'd summarize #44 by saying "we" decided to use the modified version of `Array.prototype.reduce` that returns an `Array` because it is similar to `Observable.prototype.reduce` returning an `Observable`. It's "more clear" to chain calls like `reduce().map` then it is to explain why the result types are different.  (Personally I disagree with this approach. It'd be straightforward to explain we need to return an Array so we can chain the calls. 🤷‍♂️ )

**Closed as completed** 2019-03-09 21:58 UTC
